# Dependencies
markdown:         redcarpet
highlighter:      pygments
permalink:        pretty

title:            Dust and Shadows
tagline:          "pulvis et umbra sumus"

author:
  name:           "Alex Westphal"
  url:            phantomspectre.github.io